mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('smrm.urls')),
]

smrm/urls.py
from django.conf.urls import url
import views

app_name = 'smrm'

urlpatterns = [

    url(r'^$', views.IndexViewTrash.as_view(), name='trash'),
    url(r'^trash/$', views.IndexViewTrash.as_view(), name='trash'),
    url(r'^trash/(?P<pk>[0-9]+)/$', views.DetailViewTrash.as_view(), name='detailtrash'),
    url(r'^task/(?P<pk>[0-9]+)/$', views.DetailViewTask.as_view(), name='detailtask'),
    url(r'^trash/new/$', views.addtrash, name='newtrash'),
    url(r'^task/new/$', views.addtask, name='newtask'),
    url(r'^task/$', views.IndexViewTask.as_view(), name='task'),
   
]

smrm/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from smartrm.trash import Trash as SmTrash
import os
from remover import Remover
from smartrm.remove_web import RemoveWeb

class Trash(models.Model):
    RESTORE_POLICIES = ((1, 'saveboth'),
                        (2, 'replace'))
    name = models.CharField(max_length=200, default='new trash')
    path = models.CharField(max_length=200)
    restore_policy = models.IntegerField(choices=RESTORE_POLICIES, default=1)
    max_size = models.IntegerField(default=100)
    autoclean = models.BooleanField(default=False)
    rem_period = models.IntegerField(default=-1)
    rem_size = models.IntegerField(default=-1)

    def __str__(self):
        return self.path

    def get_size(self):
        return SmTrash(self.path).get_size()

    def get_files_count(self):
        return SmTrash(self.path).files_count()

    def get_files(self):
        tr = SmTrash(self.path)
        files = tr.get_files()
        types = [self.file_type(f) for f in files]
        dict = [{'name':files[i],'type':types[i]} for i in range(len(files))]
        return dict

    def file_type(self, file):
        file = os.path.join(self.path,'files', file)
        if os.path.isdir(file):
            if len(os.listdir(file)) == 0:
                return 'empty folder'
            else:
                return 'folder'
        return 'file'


class Task(models.Model):
    STATUS_CHOICES = (
        (1, 'ready to run'),
        (2, 'processing'),
        (3, 'completed: OK'),
        (4, 'completed: error'),
        (5, 'not enough free space')
    )
    trash = models.ForeignKey(Trash)
    description = models.CharField(max_length=200)
    files = models.CharField(max_length=400)
    status = models.IntegerField(default=1, choices=STATUS_CHOICES)
    proc = models.IntegerField(default=8)
    errors = models.CharField(max_length=400, default='')
    regex = models.CharField(max_length=30, default='')

    def files_as_list(self):
        return self.files.split(',')

    def files_num(self):
        return len(self.files_as_list())

    def get_errors(self):
        return self.errors.split(',')

    def isdisabled(self):
        if self.status == 3 or self.status == 4:
            return 'disabled'

    def get_status_color(self):
        if self.status == 1:
            return 'blue'
        if self.status == 3:
            return 'green'
        if self.status == 4 or self.status == 5:
            return 'red'

    def get_files(self):
        files = self.files_as_list()
        types = []
        if self.status == 1 or self.status == 5:
            for i in range(self.files_num()):
                types.append('')
        else:
            for i in range(self.files_num()):
                if self.get_errors()[i] == '1':
                    types.append('error')
                else:
                    types.append('removed')
        dict = [{'name': files[i], 'result': types[i]} for i in range(len(files))]
        return dict

    def run(self):
        p = RemoveWeb(self.trash.path, self.trash.max_size)
        files, result = p.remove(self.files_as_list(), self.proc, self.regex)
        if result == 'err_space':
            self.status = 5
            self.save(update_fields=['status'])
            return
        if result.find('1') == -1:
            self.status = 3
        else:
            self.status = 4
        self.errors = result
        self.files = ','.join(files)
        self.save(update_fields=['status', 'errors', 'files'])

smrm/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render
from models import Trash, Task
from django.http import HttpResponseRedirect, HttpResponse
from django.views import generic, View
from trashform import TrashForm
from taskform import TaskForm
from smartrm.trash import Trash as SmTrash


class IndexViewTrash(generic.ListView):
    template_name = 'smrm/index_trash.html'
    context_object_name = 'trash_list'

    def get_queryset(self):
        return Trash.objects.all()


class IndexViewTask(generic.ListView):
    template_name = 'smrm/index_task.html'
    context_object_name = 'task_list'

    def get_queryset(self):
        return Task.objects.all()


class DetailViewTrash(generic.DetailView):
    model = Trash
    template_name = 'smrm/detail_trash.html'

    def post(self, request, pk):
        if 'del' in request.POST:
            file = request.POST.get('del')
            path = Trash.objects.get(id=pk).path
            SmTrash(path).delete_from_trash(file)
            return HttpResponseRedirect('')

        if 'rest' in request.POST:
            file = request.POST.get('rest')
            path = Trash.objects.get(id=pk).path
            SmTrash(path).restore(file)
            return HttpResponseRedirect('')

        if 'clean' in request.POST:
            path = Trash.objects.get(id=pk).path
            SmTrash(path).clean()
            return HttpResponseRedirect('')

        if 'deltrash' in request.POST:
            trash = Trash.objects.get(id=pk)
            path = trash.path
            SmTrash(path).clean()
            trash.delete()
            return HttpResponseRedirect('/trash')


class DetailViewTask(generic.DetailView):
    model = Task
    template_name = 'smrm/detail_task.html'

    def post(self, request, pk):
        if 'run' in request.POST:
            task = Task.objects.get(id=pk)
            task.run()
            return HttpResponseRedirect('')

        if 'delete' in request.POST:
            task = Task.objects.get(id=pk)
            task.delete()
            return HttpResponseRedirect('/task')


def addtrash(request):
    if request.method == 'POST':
        form = TrashForm(request.POST)
        if form.is_valid():
            t = Trash(name=form.cleaned_data['name'],
                      path=form.cleaned_data['path'],
                      restore_policy=form.cleaned_data['restore_policy'],
                      max_size=form.cleaned_data['max_size'],
                      autoclean=form.cleaned_data['autoclean'],
                      rem_period=form.cleaned_data['rem_period'],
                      rem_size=form.cleaned_data['rem_size'])
            path = form.cleaned_data['path']
            SmTrash(path).check_create()
            t.save()
            return HttpResponseRedirect('/')
    else:
        form = TrashForm()

    return render(request, 'smrm/trashform.html', {'form': form})


def addtask(request):
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            t = Task(trash=Trash.objects.get(id=form.cleaned_data['trash']),
                     files=form.cleaned_data['files'],
                     description=form.cleaned_data['description'],
                     proc=form.cleaned_data['proc'],
                     regex=form.cleaned_data['regex'])
            t.save()
            return HttpResponseRedirect('/task')
    else:
        form = TaskForm()

    return render(request, 'smrm/taskform.html', {'form': form})

smrm/templates/smrm/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jstree/3.2.1/themes/default/style.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jstree/3.2.1/jstree.min.js"></script>

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'smrm/style.css' %}" />

    <title>{% block title %}SmartRm{% endblock %}</title>
</head>
<body>
    <nav class="navbar">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand">SmartRm</a>
        </div>
        <ul class="nav navbar-nav">
          <li><a href="{% url 'smrm:trash' %}">Trashes</a></li>
          <li><a href="{% url 'smrm:task' %}">Tasks</a></li>
          <li><a href="{% url 'smrm:newtask' %}">New Task</a></li>
        </ul>
      </div>
    </nav>

    <div class="container">
        <h1>{% block heading %}{% endblock %}</h1>
    </div>

    <div class="container">
        {% block body %}

        {% endblock %}
    </div>


    <footer>
    </footer>
</body>
</html>

smrm/templates/smrm/detail_task.html
{% extends 'smrm/base.html' %}
{% block title %}
    Task {{ task.id }}
{% endblock %}


{% block body %}
    <h1>{{ task.description }}</h1>
    <p>trash: {{ task.trash.path }}</p>
    <p>status:
        <span style="color: {{ task.get_status_color }}">{{ task.get_status_display }}</span>
    </p>
    <p>processes number: {{ task.proc }}</p>
    {%  if task.regex %}
    <p>regex: {{ task.regex }}</p>
    {% endif %}
    <table class="table">
            <thead>
            <tr><th>Files</th></tr>
            </thead>
            <tbody>
             {% for f in task.get_files %}
                    <tr>
                        <td>{{f.name}}</td>
                        <td>{{ f.result }}</td>
                    </tr>
            {% endfor %}
            </tbody>
        </table>

    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-default btn-md " name="run" value="run" {{ task.isdisabled }} >
        <input type="submit" class="btn btn-default btn-md" name="delete" value="delete task">
    </form>
{% endblock %}

smrm/templates/smrm/detail_trash.html
{% extends 'smrm/base.html' %}
{% block title %}
    {{ trash.name }}
{% endblock %}


{% block body %}
        <h1>{{ trash.name }}</h1>
        <p>{{trash.path}}</p>
        <p>{{trash.get_size}} Mbs / {{ trash.max_size }} Mbs</p>
        <p>{{trash.get_files_count}} files</p>
        <p>restore policy: {{ trash.get_restore_policy_display }}</p>
        <p>autoclean: {{ trash.autoclean }}</p>
        {% if trash.autoclean %}
            <p>remove period:
                {% if trash.rem_period > 0 %}{{ trash.rem_period }} days
                {% else %}none{% endif %} </p>
            <p>remove size:
                {% if trash.rem_size > 0 %}{{ trash.rem_size }} Mbs
                {% else %}none{% endif %} </p>
        {% endif %}
        <table class="table">
            <thead>
            <tr><th>Files</th></tr>
            </thead>
            <tbody>
             {% for f in trash.get_files %}
                    <tr>
                        <td>{{f.name}}</td>
                        <td>{{ f.type }}</td>
                        <td>
                            <button class="btn btn-default btn-sm" type="submit" form="form" name="del" value="{{ f.name }}">delete</button>
                        </td>
                        <td>
                            <button class="btn btn-default btn-sm" type="submit" form="form" name="rest" value="{{ f.name }}">restore</button>
                        </td>
                    </tr>

            {% endfor %}
            </tbody>
        </table>

        <button class="btn btn-default btn-md" type="submit" form="form" name="clean">clean trash</button>
        <button class="btn btn-default btn-md" type="submit" form="form" name="deltrash">delete trash</button>

        <form method="post" id="form">
            {% csrf_token %}
        </form>
{% endblock %}

smrm/templates/smrm/index_task.html
{% extends 'smrm/base.html' %}

{% block title %}
    Tasks
{% endblock %}

{% block heading %}
    Tasks
{% endblock %}

{% block body %}
           {% if task_list %}
                <div class="list-group">
                {% for task in task_list %}
                    <a href="{% url 'smrm:detailtask' task.id %}" class="list-group-item">
                    <div class="container">
                        <div class="row">
                        <div class="col-sm-6">
                        <h4 class="list-group-item-heading">Task {{ task.id }} </h4>
                            <p class="list-group-item-heading">to: {{ task.trash.name }} </p>
                        <p class="list-group-item-heading">{{ task.description }} </p>

                        </div>
                        <div class="col-sm-6">
                            <p> {{ task.files_num }} file{{ task.files_num|pluralize:'s' }}</p>
                            <p class="list-group-item-text">status:
                                <span style="color: {{ task.get_status_color }}">{{ task.get_status_display }}</span>
                            </p>
                        </div>
                        </div>
                    </div>
                    </a>
                {% endfor %}
                </div>
            {% else %}
                <p>No tasks are available.</p>
            {% endif %}
        <a href="{% url 'smrm:newtask' %}" class="btn btn-default btn-lg">Add</a>
{% endblock %}

smrm/templates/smrm/index_trash.html
{% extends 'smrm/base.html' %}

{% block title %}
    Trashes
{% endblock %}

{% block heading %}
    Trashes
{% endblock %}

{% block body %}
            {% if trash_list %}
                <div class="list-group">
                {% for trash in trash_list %}
                    <a href="{% url 'smrm:detailtrash' trash.id %}" class="list-group-item">
                        <h4 class="list-group-item-heading">{{ trash.name }} </h4>
                        <p class="list-group-item-text">{{ trash.path }} </p>
                    </a>
                {% endfor %}
                </div>
            {% else %}
                <p>No trashes are available.</p>
            {% endif %}
        <a href="{% url 'smrm:newtrash' %}" class="btn btn-default btn-lg">Add</a>
{% endblock %}

smrm/templates/smrm/taskform.html
{% extends 'smrm/base.html' %}
{% block title %}
    New task
{% endblock %}




{% block heading %}
    New task
{% endblock %}

{% block body %}
    {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
    {% endif %}
    <form id="form" class="form-horizontal" method="post" novalidate>
        <table>
            {{ form.as_table }}
        </table>
        <label for="tree">Files:</label>
        <div id="tree">
            {{ form.maketree|safe }}
        </div>
        {% csrf_token %}
        <input id="mbut" type="submit"  value="Create">
        {% load static %}
        <script type="text/javascript" src="{% static "smrm/tree.js" %}"></script>
    </form>

{% endblock %}

smrm/templates/smrm/trashform.html
{% extends 'smrm/base.html' %}

    {% block title %}
        New trash
    {% endblock %}

    {% block heading %}
        New trash
    {% endblock %}

    {% block body %}
    {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
    {% endif %}

    <form action="" method="post" novalidate>
        <table>
            {{ form.as_table }}
        </table>
        {% csrf_token %}
        <input type="submit" value="Create">
    </form>
    {% endblock %}